/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppFeedRouteImport } from './routes/_app/_feed'
import { Route as AppDraftIndexRouteImport } from './routes/_app/draft/index'
import { Route as AppProfileUserIdIndexRouteImport } from './routes/_app/profile/$userId/index'
import { Route as AppProfileUserIdIntentionIntentionIdRouteImport } from './routes/_app/profile/$userId/intention/$intentionId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/_feed',
  getParentRoute: () => AppRoute,
} as any)
const AppDraftIndexRoute = AppDraftIndexRouteImport.update({
  id: '/draft/',
  path: '/draft/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdIndexRoute = AppProfileUserIdIndexRouteImport.update({
  id: '/profile/$userId/',
  path: '/profile/$userId/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdIntentionIntentionIdRoute =
  AppProfileUserIdIntentionIntentionIdRouteImport.update({
    id: '/profile/$userId/intention/$intentionId',
    path: '/profile/$userId/intention/$intentionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppFeedRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/draft/': typeof AppDraftIndexRoute
  '/profile/$userId/': typeof AppProfileUserIdIndexRoute
  '/profile/$userId/intention/$intentionId': typeof AppProfileUserIdIntentionIntentionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppFeedRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/draft': typeof AppDraftIndexRoute
  '/profile/$userId': typeof AppProfileUserIdIndexRoute
  '/profile/$userId/intention/$intentionId': typeof AppProfileUserIdIntentionIntentionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/_feed': typeof AppFeedRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/search': typeof AppSearchRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/draft/': typeof AppDraftIndexRoute
  '/_app/profile/$userId/': typeof AppProfileUserIdIndexRoute
  '/_app/profile/$userId/intention/$intentionId': typeof AppProfileUserIdIntentionIntentionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/search'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/draft/'
    | '/profile/$userId/'
    | '/profile/$userId/intention/$intentionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/search'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/draft'
    | '/profile/$userId'
    | '/profile/$userId/intention/$intentionId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/_feed'
    | '/_app/notifications'
    | '/_app/search'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/draft/'
    | '/_app/profile/$userId/'
    | '/_app/profile/$userId/intention/$intentionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_feed': {
      id: '/_app/_feed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/draft/': {
      id: '/_app/draft/'
      path: '/draft'
      fullPath: '/draft/'
      preLoaderRoute: typeof AppDraftIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId/': {
      id: '/_app/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof AppProfileUserIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId/intention/$intentionId': {
      id: '/_app/profile/$userId/intention/$intentionId'
      path: '/profile/$userId/intention/$intentionId'
      fullPath: '/profile/$userId/intention/$intentionId'
      preLoaderRoute: typeof AppProfileUserIdIntentionIntentionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFeedRoute: typeof AppFeedRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppDraftIndexRoute: typeof AppDraftIndexRoute
  AppProfileUserIdIndexRoute: typeof AppProfileUserIdIndexRoute
  AppProfileUserIdIntentionIntentionIdRoute: typeof AppProfileUserIdIntentionIntentionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFeedRoute: AppFeedRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSearchRoute: AppSearchRoute,
  AppDraftIndexRoute: AppDraftIndexRoute,
  AppProfileUserIdIndexRoute: AppProfileUserIdIndexRoute,
  AppProfileUserIdIntentionIntentionIdRoute:
    AppProfileUserIdIntentionIntentionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
